version: "3.9"

services:
  cloud-gateway:
    image: alpine/java:21-jdk
    container_name: cloud-gateway
    #restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1.0'     
    ports:
      - "9090:9090"
    volumes:
      - ./target/cloud-gateway-0.0.1-SNAPSHOT.jar:/app/cloud-gateway-v1.jar
    command: ["java", "-jar", "/app/cloud-gateway-v1.jar"]
    networks:
      - mitocode

networks:
  mitocode:
    name: mitocode-network